import SwiftUI
import SwiftData

/// Represents a piece of knowledge or information about the student that the AI remembers
@Model
class StudentKnowledge {
    var id: UUID
    var content: String
    var category: KnowledgeCategory
    var subjectId: String
    var masteryLevel: Double  // 0.0 - 1.0 (0% to 100% mastery)
    var createdAt: Date
    var lastReviewedAt: Date
    var timesReferenced: Int

    init(
        content: String,
        category: KnowledgeCategory,
        subjectId: String,
        masteryLevel: Double = 0.5
    ) {
        self.id = UUID()
        self.content = content
        self.category = category
        self.subjectId = subjectId
        self.masteryLevel = masteryLevel
        self.createdAt = Date()
        self.lastReviewedAt = Date()
        self.timesReferenced = 0
    }

    /// Updates the last reviewed timestamp and increments reference count
    func markAsReferenced() {
        lastReviewedAt = Date()
        timesReferenced += 1
    }

    /// Updates mastery level (clamped between 0 and 1)
    func updateMastery(_ newLevel: Double) {
        masteryLevel = max(0, min(1, newLevel))
        lastReviewedAt = Date()
    }
}

/// Categories of knowledge the AI can store about a student
enum KnowledgeCategory: String, Codable, CaseIterable {
    case concept = "concept"              // "entiende derivadas", "sabe la tabla del 7"
    case difficulty = "difficulty"        // "tiene dificultad con fracciones"
    case preference = "preference"        // "prefiere ejemplos visuales"
    case interest = "interest"            // "le interesa astronomía"
    case misconception = "misconception"  // "confunde velocidad con aceleración"
    case strength = "strength"            // "es muy bueno en álgebra"
    case goal = "goal"                    // "quiere estudiar medicina"

    var displayName: String {
        switch self {
        case .concept: return "Concepto aprendido"
        case .difficulty: return "Área de dificultad"
        case .preference: return "Preferencia de aprendizaje"
        case .interest: return "Interés"
        case .misconception: return "Concepto erróneo"
        case .strength: return "Fortaleza"
        case .goal: return "Meta"
        }
    }

    var icon: String {
        switch self {
        case .concept: return "checkmark.circle.fill"
        case .difficulty: return "exclamationmark.triangle.fill"
        case .preference: return "heart.fill"
        case .interest: return "star.fill"
        case .misconception: return "xmark.circle.fill"
        case .strength: return "bolt.fill"
        case .goal: return "flag.fill"
        }
    }

    var color: Color {
        switch self {
        case .concept: return .green
        case .difficulty: return .orange
        case .preference: return .pink
        case .interest: return .yellow
        case .misconception: return .red
        case .strength: return .blue
        case .goal: return .purple
        }
    }
}

/// Represents a quiz question generated by the AI
@Model
class QuizQuestion {
    var id: UUID
    var question: String
    var options: [String]  // For multiple choice
    var correctAnswer: String
    var explanation: String
    var subjectId: String
    var relatedConcept: String
    var difficulty: QuizDifficulty
    var wasAnsweredCorrectly: Bool?
    var createdAt: Date
    var answeredAt: Date?

    init(
        question: String,
        options: [String],
        correctAnswer: String,
        explanation: String,
        subjectId: String,
        relatedConcept: String,
        difficulty: QuizDifficulty = .medium
    ) {
        self.id = UUID()
        self.question = question
        self.options = options
        self.correctAnswer = correctAnswer
        self.explanation = explanation
        self.subjectId = subjectId
        self.relatedConcept = relatedConcept
        self.difficulty = difficulty
        self.wasAnsweredCorrectly = nil
        self.createdAt = Date()
        self.answeredAt = nil
    }

    func recordAnswer(wasCorrect: Bool) {
        wasAnsweredCorrectly = wasCorrect
        answeredAt = Date()
    }
}

enum QuizDifficulty: String, Codable, CaseIterable {
    case easy = "easy"
    case medium = "medium"
    case hard = "hard"

    var displayName: String {
        switch self {
        case .easy: return "Fácil"
        case .medium: return "Medio"
        case .hard: return "Difícil"
        }
    }

    var color: Color {
        switch self {
        case .easy: return .green
        case .medium: return .orange
        case .hard: return .red
        }
    }
}

/// Tracks a learning plan created by the AI
@Model
class LearningPlan {
    var id: UUID
    var topic: String
    var subjectId: String
    var steps: [LearningStep]
    var currentStepIndex: Int
    var isCompleted: Bool
    var createdAt: Date
    var completedAt: Date?

    init(topic: String, subjectId: String, steps: [LearningStep]) {
        self.id = UUID()
        self.topic = topic
        self.subjectId = subjectId
        self.steps = steps
        self.currentStepIndex = 0
        self.isCompleted = false
        self.createdAt = Date()
        self.completedAt = nil
    }

    var currentStep: LearningStep? {
        guard currentStepIndex < steps.count else { return nil }
        return steps[currentStepIndex]
    }

    var progress: Double {
        guard !steps.isEmpty else { return 0 }
        return Double(currentStepIndex) / Double(steps.count)
    }

    func advanceToNextStep() {
        if currentStepIndex < steps.count - 1 {
            currentStepIndex += 1
        } else {
            isCompleted = true
            completedAt = Date()
        }
    }
}

/// A single step in a learning plan
struct LearningStep: Codable, Identifiable {
    var id: UUID
    var title: String
    var description: String
    var prerequisite: String?
    var isCompleted: Bool

    init(title: String, description: String, prerequisite: String? = nil) {
        self.id = UUID()
        self.title = title
        self.description = description
        self.prerequisite = prerequisite
        self.isCompleted = false
    }
}
