import Foundation
import FoundationModels
import Observation
import SwiftData

// TODO: Singleton + @Observable can cause unintended UI updates across unrelated views.
// Consider splitting into a non-Observable singleton for session management and a separate
// @Observable state object owned by the ViewModel.
@Observable
@MainActor
class FoundationModelService {
    static let shared = FoundationModelService()
    private var session: LanguageModelSession?
    private var currentSubject: Subject?
    enum InteractionMode {
        case text
        case voice
    }

    var isGenerating = false
    private var currentInteractionMode: InteractionMode = .text

    /// Image generation state for UI feedback
    var imageGenerationState: ImageGenerationState = .idle

    /// The generated image URL (if any) for the current response
    var generatedImageURL: URL?

    /// Quiz generated state
    var lastGeneratedQuiz: QuizQuestion?

    /// Interactive attachment generated by tool (type, json_data)
    var generatedAttachment: (type: String, data: String)?

    // MARK: - Tools
    private var imageTool: ImageGeneratorTool?
    private var memoryStoreTool: MemoryStoreTool?
    private var memoryRecallTool: MemoryRecallTool?
    private var quizTool: QuizGeneratorTool?
    private var questTool: DailyQuestGeneratorTool?

    /// Whether the current session has tools (used to select generation options)
    private var sessionHasTools = false

    /// Generation options: greedy for tool-calling sessions (more deterministic tool selection)
    private var generationOptions: GenerationOptions {
        sessionHasTools
            ? GenerationOptions(sampling: .greedy)
            : GenerationOptions()
    }

    /// Student context for adaptive prompts
    private var studentName: String = "Estudiante"
    private var educationLevel: EducationLevel = .secondary

    /// Model context for SwiftData operations (set externally)
    var modelContext: ModelContext?

    /// Student knowledge context (built from memory)
    private var studentKnowledgeContext: String = ""

    /// Checks if Foundation Models are available on this device
    var isAvailable: Bool {
        SystemLanguageModel.default.availability == .available
    }

    /// Returns the availability status for UI handling
    var availability: SystemLanguageModel.Availability {
        SystemLanguageModel.default.availability
    }

    // MARK: - Session Creation

    func createSession(
        for subject: Subject,
        studentName: String = "Estudiante",
        educationLevel: EducationLevel = .secondary,
        interactionMode: InteractionMode = .text,
        forceRecreate: Bool = false
    ) {
        // Skip recreation if session already exists for same subject and settings
        // This preserves the internal session state when user re-enters a chat
        if !forceRecreate,
           session != nil,
           currentSubject == subject,
           self.studentName == studentName,
           self.educationLevel == educationLevel,
           self.currentInteractionMode == interactionMode {
            // Just update knowledge context in case it changed
            if let context = modelContext {
                studentKnowledgeContext = StudentMemoryService.shared.buildKnowledgeContext(
                    for: subject.id,
                    context: context
                )
            }
            return
        }

        self.currentSubject = subject
        self.studentName = studentName
        self.educationLevel = educationLevel
        self.currentInteractionMode = interactionMode

        // Reset states
        generatedImageURL = nil
        imageGenerationState = .idle
        lastGeneratedQuiz = nil

        // Build student knowledge context if we have a model context
        if let context = modelContext {
            studentKnowledgeContext = StudentMemoryService.shared.buildKnowledgeContext(
                for: subject.id,
                context: context
            )
        }

        // Build tools - voice mode uses minimal tools to fit context window
        var tools: [any Tool] = []

        if interactionMode == .voice {
            // Voice mode: only memory tools to keep context small
            let storeTool = MemoryStoreTool()
            configureMemoryStoreTool(storeTool, subjectId: subject.id)
            tools.append(storeTool)
            self.memoryStoreTool = storeTool

            let recallTool = MemoryRecallTool()
            configureMemoryRecallTool(recallTool, subjectId: subject.id)
            tools.append(recallTool)
            self.memoryRecallTool = recallTool

            // Clear unused tool references
            self.imageTool = nil
            self.quizTool = nil
            self.questTool = nil
        } else {
            // Text mode: subject-aware tool selection (max 3-4 tools to fit context window)

            // Clear all tool references first
            self.imageTool = nil
            self.quizTool = nil
            self.questTool = nil

            // 1. Memory Store Tool (always)
            let storeTool = MemoryStoreTool()
            configureMemoryStoreTool(storeTool, subjectId: subject.id)
            tools.append(storeTool)
            self.memoryStoreTool = storeTool

            // 2. Memory Recall Tool (always)
            let recallTool = MemoryRecallTool()
            configureMemoryRecallTool(recallTool, subjectId: subject.id)
            tools.append(recallTool)
            self.memoryRecallTool = recallTool

            // 3+. Subject-specific tools
            switch subject {
            case .math, .physics, .chemistry:
                // STEM: Quiz + Geometry
                let qTool = QuizGeneratorTool()
                configureQuizTool(qTool, subjectId: subject.id)
                tools.append(qTool)
                self.quizTool = qTool

                let geomTool = GeometryTool()
                configureGeometryTool(geomTool)
                tools.append(geomTool)

            case .science, .social, .arts, .sports:
                // Visual subjects: ImageGenerator
                if subject.supportsImages {
                    let imgTool = ImageGeneratorTool()
                    configureImageTool(imgTool)
                    tools.append(imgTool)
                    self.imageTool = imgTool
                    Task { await imgTool.prepare() }
                }

            case .language, .english, .ethics, .technology:
                // Text-heavy subjects: Quiz
                let qTool = QuizGeneratorTool()
                configureQuizTool(qTool, subjectId: subject.id)
                tools.append(qTool)
                self.quizTool = qTool

            case .open:
                // General chat: Image + Geometry (max 4 tools total with memory)
                // Keeping tool count low prevents context window saturation on-device.
                // Quest tool omitted here — quests are triggered from HomeView, not chat.
                let imgTool = ImageGeneratorTool()
                configureImageTool(imgTool)
                tools.append(imgTool)
                self.imageTool = imgTool
                Task { await imgTool.prepare() }

                let geomTool = GeometryTool()
                configureGeometryTool(geomTool)
                tools.append(geomTool)
            }
        }

        // Get system prompt with all tool instructions
        let systemPrompt = getSystemPrompt(
            for: subject,
            includeImageInstructions: subject.supportsImages && imageTool != nil,
            mode: interactionMode
        )

        // Track whether this session has tools (for generation options selection)
        sessionHasTools = !tools.isEmpty

        // Create session with all tools
        if tools.isEmpty {
            session = LanguageModelSession {
                systemPrompt
            }
        } else {
            session = LanguageModelSession(tools: tools) {
                systemPrompt
            }
        }
    }

    // MARK: - Tool Configuration

    private func configureImageTool(_ tool: ImageGeneratorTool) {
        tool.onGenerationStarted = { [weak self] reason in
            Task { @MainActor in
                self?.imageGenerationState = .generating(prompt: reason)
            }
        }

        tool.onImageGenerated = { [weak self] url in
            Task { @MainActor in
                self?.generatedImageURL = url
                self?.imageGenerationState = .completed(imageURL: url)
            }
        }

        tool.onGenerationFailed = { [weak self] error in
            Task { @MainActor in
                self?.imageGenerationState = .failed(error: error)
            }
        }
    }

    private func configureMemoryStoreTool(_ tool: MemoryStoreTool, subjectId: String) {
        tool.currentSubjectId = subjectId
        tool.onStoreKnowledge = { [weak self] content, category, mastery in
            Task { @MainActor in
                guard let context = self?.modelContext else { return }
                _ = StudentMemoryService.shared.storeKnowledge(
                    content: content,
                    category: category,
                    subjectId: subjectId,
                    masteryLevel: mastery,
                    context: context
                )
            }
        }
    }

    private func configureMemoryRecallTool(_ tool: MemoryRecallTool, subjectId: String) {
        tool.onRecallKnowledge = { [weak self] queryType, topic in
            guard let context = self?.modelContext else {
                return "No hay información disponible."
            }

            switch queryType.lowercased() {
            case "profile", "perfil":
                return StudentMemoryService.shared.generateStudentProfile(
                    for: subjectId,
                    context: context
                )

            case "concepts", "conceptos":
                let concepts = StudentMemoryService.shared.getKnowledge(
                    for: subjectId,
                    category: .concept,
                    context: context
                )
                if concepts.isEmpty { return "No hay conceptos registrados." }
                return concepts.map { "• \($0.content) (dominio: \(Int($0.masteryLevel * 100))%)" }.joined(separator: "\n")

            case "difficulties", "dificultades":
                let diffs = StudentMemoryService.shared.getDifficulties(for: subjectId, context: context)
                if diffs.isEmpty { return "No hay dificultades registradas." }
                return diffs.map { "• \($0.content)" }.joined(separator: "\n")

            case "interests", "intereses":
                let interests = StudentMemoryService.shared.getInterests(context: context)
                if interests.isEmpty { return "No hay intereses registrados." }
                return interests.map { "• \($0.content)" }.joined(separator: "\n")

            default: // "all"
                return StudentMemoryService.shared.buildKnowledgeContext(
                    for: subjectId,
                    context: context
                )
            }
        }
    }

    private func configureQuizTool(_ tool: QuizGeneratorTool, subjectId: String) {
        tool.onQuizGenerated = { [weak self] question, options, correct, explanation, concept, difficulty in
            Task { @MainActor in
                guard let context = self?.modelContext else { return }
                let quiz = StudentMemoryService.shared.storeQuizQuestion(
                    question: question,
                    options: options,
                    correctAnswer: correct,
                    explanation: explanation,
                    subjectId: subjectId,
                    relatedConcept: concept,
                    difficulty: difficulty,
                    context: context
                )
                self?.lastGeneratedQuiz = quiz
            }
        }
    }

    private func configureQuestTool(_ tool: DailyQuestGeneratorTool, subjectId: String) {
        tool.currentSubjectId = subjectId
        tool.onQuestGenerated = { [weak self] quest in
            Task { @MainActor in
                guard let context = self?.modelContext else { return }
                DailyQuestService.shared.saveGeneratedQuest(quest, context: context)
            }
        }
    }
    
    private func configureGeometryTool(_ tool: GeometryTool) {
        tool.onGeometryGenerated = { [weak self] jsonString in
            Task { @MainActor in
                self?.generatedAttachment = ("geometry_3d", jsonString)
            }
        }
    }

    // MARK: - Response Streaming

    func streamResponse(
        prompt: String,
        history: [ChatMessage]
    ) -> AsyncThrowingStream<String, Error> {
        self.isGenerating = true
        self.generatedImageURL = nil
        self.imageGenerationState = .idle
        self.lastGeneratedQuiz = nil
        self.generatedAttachment = nil

        return AsyncThrowingStream { continuation in
            Task {
                defer {
                    self.isGenerating = false
                }

                // Auto-recrear session si se perdió
                if self.session == nil, let subject = self.currentSubject {
                    self.createSession(for: subject, studentName: self.studentName, educationLevel: self.educationLevel, forceRecreate: true)
                    // Replay recent history into the fresh session so the model has context
                    await self.replayHistory(history, into: self.session)
                }

                guard let session = self.session else {
                    continuation.finish(throwing: NovaError.noSession)
                    return
                }

                do {
                    let stream = session.streamResponse(to: prompt, options: self.generationOptions)

                    var lastRawCount = 0
                    var lastCleanedCount = 0
                    var pendingNewChars = 0
                    var lastRawText = ""
                    // Only run full regex cleaning every N new characters to reduce overhead.
                    // For a 500-token response this cuts regex passes from ~500 to ~15.
                    let cleaningThreshold = 32

                    for try await partialResponse in stream {
                        let currentText = partialResponse.content
                        if currentText.count > lastRawCount {
                            pendingNewChars += currentText.count - lastRawCount
                            lastRawCount = currentText.count
                            lastRawText = currentText

                            // Batch cleaning: only run regex when enough new content has accumulated
                            if pendingNewChars >= cleaningThreshold {
                                let cleanedFullText = self.cleanResponseText(currentText)
                                pendingNewChars = 0

                                if cleanedFullText.count > lastCleanedCount {
                                    let cleanedIndex = cleanedFullText.index(cleanedFullText.startIndex, offsetBy: lastCleanedCount)
                                    let cleanedDelta = String(cleanedFullText[cleanedIndex...])
                                    continuation.yield(cleanedDelta)
                                    lastCleanedCount = cleanedFullText.count
                                }
                            }
                        }
                    }

                    // Final clean pass to flush any remaining buffered content
                    if pendingNewChars > 0, !lastRawText.isEmpty {
                        let cleanedFullText = self.cleanResponseText(lastRawText)
                        if cleanedFullText.count > lastCleanedCount {
                            let cleanedIndex = cleanedFullText.index(cleanedFullText.startIndex, offsetBy: lastCleanedCount)
                            let cleanedDelta = String(cleanedFullText[cleanedIndex...])
                            continuation.yield(cleanedDelta)
                        }
                    }

                    continuation.finish()
                } catch {
                    // Check if this is a context window overflow
                    let isContextOverflow: Bool
                    if let genError = error as? LanguageModelSession.GenerationError,
                       case .exceededContextWindowSize = genError {
                        isContextOverflow = true
                    } else {
                        isContextOverflow = false
                    }

                    if isContextOverflow, let subject = self.currentSubject {
                        // Context overflow recovery: reset session and retry once
                        // Only replay the last few messages to avoid overflowing again
                        self.createSession(
                            for: subject,
                            studentName: self.studentName,
                            educationLevel: self.educationLevel,
                            interactionMode: self.currentInteractionMode,
                            forceRecreate: true
                        )
                        // Replay a small window of recent history for context
                        let recentHistory = Array(history.suffix(4))
                        await self.replayHistory(recentHistory, into: self.session)

                        if let newSession = self.session {
                            do {
                                let retryStream = newSession.streamResponse(to: prompt, options: self.generationOptions)
                                var retryLastRawCount = 0
                                var retryLastCleanedCount = 0
                                var retryPendingNewChars = 0
                                var retryLastRawText = ""

                                for try await partialResponse in retryStream {
                                    let text = partialResponse.content
                                    if text.count > retryLastRawCount {
                                        retryPendingNewChars += text.count - retryLastRawCount
                                        retryLastRawCount = text.count
                                        retryLastRawText = text

                                        if retryPendingNewChars >= 32 {
                                            let cleaned = self.cleanResponseText(text)
                                            retryPendingNewChars = 0
                                            if cleaned.count > retryLastCleanedCount {
                                                let idx = cleaned.index(cleaned.startIndex, offsetBy: retryLastCleanedCount)
                                                continuation.yield(String(cleaned[idx...]))
                                                retryLastCleanedCount = cleaned.count
                                            }
                                        }
                                    }
                                }

                                // Final flush
                                if retryPendingNewChars > 0, !retryLastRawText.isEmpty {
                                    let cleaned = self.cleanResponseText(retryLastRawText)
                                    if cleaned.count > retryLastCleanedCount {
                                        let idx = cleaned.index(cleaned.startIndex, offsetBy: retryLastCleanedCount)
                                        continuation.yield(String(cleaned[idx...]))
                                    }
                                }

                                continuation.finish()
                                return
                            } catch {
                                continuation.finish(throwing: NovaError.contextLimitExceeded)
                                return
                            }
                        }
                        continuation.finish(throwing: NovaError.contextLimitExceeded)
                    } else {
                        continuation.finish(throwing: error)
                    }
                }
            }
        }
    }

    // MARK: - Cached Regex Patterns (compiled once, thread-safe)

    /// Removes markdown images, base64 patterns, and leaked tool logs from text
    nonisolated private func cleanResponseText(_ text: String) -> String {
        var cleaned = text
        
        // Swift 6 / iOS 26 Standard: Use native Regex for concurrency safety
        for regex in CleaningPatterns.patterns {
            cleaned.replace(regex, with: "")
        }

        let result = cleaned.trimmingCharacters(in: .whitespacesAndNewlines)
        
        // Safety Fallback: If cleaning removed everything but the input was not empty, 
        // return the original text to avoid "silent" failures.
        if result.isEmpty && !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return text
        }
        
        return result
    }

    /// Non-streaming response for simpler use cases
    func respond(to prompt: String, history: [ChatMessage]) async throws -> String {
        // Auto-recrear session si se perdió
        if session == nil, let subject = currentSubject {
            createSession(for: subject, studentName: studentName, educationLevel: educationLevel, forceRecreate: true)
            await replayHistory(history, into: session)
        }

        guard let session = session else {
            throw NovaError.noSession
        }

        isGenerating = true
        generatedImageURL = nil
        imageGenerationState = .idle

        defer {
            isGenerating = false
        }

        do {
            let response = try await session.respond(to: prompt, options: generationOptions)
            return cleanResponseText(response.content)
        } catch {
            // Check if this is a context window overflow
            if let genError = error as? LanguageModelSession.GenerationError,
               case .exceededContextWindowSize = genError,
               let subject = self.currentSubject {
                // Context overflow recovery: reset session and retry once
                self.createSession(
                    for: subject,
                    studentName: self.studentName,
                    educationLevel: self.educationLevel,
                    interactionMode: self.currentInteractionMode,
                    forceRecreate: true
                )
                // Replay a small window of recent history for context
                let recentHistory = Array(history.suffix(4))
                await replayHistory(recentHistory, into: self.session)

                if let newSession = self.session {
                    let retryResponse = try await newSession.respond(to: prompt, options: generationOptions)
                    return cleanResponseText(retryResponse.content)
                }
                throw NovaError.contextLimitExceeded
            }
            throw error
        }
    }

    /// Replays recent conversation history into a fresh session to restore context.
    /// This is used when a session is recreated (e.g., after context overflow or auto-recovery).
    /// Only the last few messages are replayed to avoid re-overflowing the context window.
    private func replayHistory(_ history: [ChatMessage], into session: LanguageModelSession?) async {
        guard let session = session else { return }

        // Take the last few exchanges (user+assistant pairs) to keep context compact
        let recentMessages = history.suffix(6)
        guard !recentMessages.isEmpty else { return }

        // Build a compact summary of recent conversation for the model
        var contextSummary = "Recent conversation summary with \(studentName):\n"
        for msg in recentMessages {
            let role = msg.role == .user ? studentName : "Nova"
            // Truncate long messages to save context tokens
            let content = msg.content.count > 200
                ? String(msg.content.prefix(200)) + "..."
                : msg.content
            contextSummary += "\(role): \(content)\n"
        }
        contextSummary += "\nContinue the conversation considering this prior context. Always respond in Spanish."

        // Send the summary as a prompt so it enters the transcript, then discard the response
        _ = try? await session.respond(to: contextSummary)
    }

    /// Prewarms the on-device language model for faster first response
    func prewarmSession() {
        Task {
            do {
                try await SystemLanguageModel.default.prewarm()
            } catch {
                // Prewarm failed silently — model will load on first request
            }
        }
    }

    func cancel() {
        isGenerating = false
        imageGenerationState = .idle
    }

    private var imageResetTask: Task<Void, Never>?

    /// Resets the image generation state after it's been processed
    func resetImageState() {
        generatedImageURL = nil
        // Cancel any pending reset to avoid stale closures
        imageResetTask?.cancel()

        let delay: Duration = if case .failed = imageGenerationState { .seconds(3) } else { .seconds(2) }

        if case .completed = imageGenerationState {
            imageResetTask = Task {
                try? await Task.sleep(for: delay)
                guard !Task.isCancelled else { return }
                if case .completed = self.imageGenerationState {
                    self.imageGenerationState = .idle
                }
            }
        } else if case .failed = imageGenerationState {
            imageResetTask = Task {
                try? await Task.sleep(for: delay)
                guard !Task.isCancelled else { return }
                if case .failed = self.imageGenerationState {
                    self.imageGenerationState = .idle
                }
            }
        }
    }


    // MARK: - System Prompt Generation

    private func getSystemPrompt(for subject: Subject, includeImageInstructions: Bool, mode: InteractionMode) -> String {
        let subjectPrompt: String

        switch subject {
        case .math:
            subjectPrompt = """
            You are \(studentName)'s mathematics tutor. Answer directly for simple calculations. \
            Explain complex problems step by step. Use LaTeX: $...$ inline, $$...$$ blocks. \
            Guide \(studentName) to find their own errors. IMPORTANT: Always respond in Spanish.
            """
        case .physics:
            subjectPrompt = """
            You are \(studentName)'s physics tutor. Explain phenomena intuitively with everyday examples. \
            Use LaTeX for formulas. Include SI units. Encourage reasoning before formulas. \
            IMPORTANT: Always respond in Spanish.
            """
        case .chemistry:
            subjectPrompt = """
            You are \(studentName)'s chemistry tutor. Explain reactions step by step. \
            Use correct chemical notation and LaTeX. Balance equations showing the process. \
            Relate to daily life. IMPORTANT: Always respond in Spanish.
            """
        case .science:
            subjectPrompt = """
            You are \(studentName)'s natural sciences guide. Foster curiosity and the scientific method. \
            Use simple analogies. Relate to the environment. IMPORTANT: Always respond in Spanish.
            """
        case .social:
            subjectPrompt = """
            You are \(studentName)'s social sciences and history tutor. Explain historical context and causes/consequences. \
            Promote critical thinking. Be impartial. IMPORTANT: Always respond in Spanish.
            """
        case .language:
            subjectPrompt = """
            You are \(studentName)'s Language and Literature tutor. Help with spelling, grammar, and writing. \
            Explain rules with clear examples. IMPORTANT: Always respond in Spanish.
            """
        case .english:
            subjectPrompt = """
            You are \(studentName)'s English tutor. Explain in Spanish how things are said in English. \
            Use **bold** for English vocabulary. Encourage practice. IMPORTANT: Always respond in Spanish.
            """
        case .ethics:
            subjectPrompt = """
            You are \(studentName)'s Ethics and Values guide. Help reflect, do not impose opinions. \
            Present multiple perspectives. Use hypothetical scenarios. IMPORTANT: Always respond in Spanish.
            """
        case .technology:
            subjectPrompt = """
            You are \(studentName)'s Technology tutor. Explain programming, hardware, and cybersecurity. \
            Use Markdown code blocks. IMPORTANT: Always respond in Spanish.
            """
        case .arts:
            subjectPrompt = """
            You are \(studentName)'s creative companion in Arts. Explore art history, techniques, and creative expression. \
            Suggest practical exercises. IMPORTANT: Always respond in Spanish.
            """
        case .sports:
            subjectPrompt = """
            You are \(studentName)'s Physical Education coach. Promote healthy living and teamwork. \
            Explain rules and strategies. You are not a doctor. IMPORTANT: Always respond in Spanish.
            """
        case .open:
            subjectPrompt = """
            You are \(studentName)'s personal educational assistant. Be direct for concrete facts. \
            Be conversational. Acknowledge limits. Friendly and helpful tone. IMPORTANT: Always respond in Spanish.
            """
        }

        // Build the full prompt with identity, student context, and subject instructions
        let identityBlock = buildIdentityBlock()
        let studentContext = buildStudentContext()
        let knowledgeBlock = buildKnowledgeBlock()
        let toolInstructions = buildToolInstructions(for: subject, includeImageInstructions: includeImageInstructions)

        if mode == .voice {
            return """
            \(identityBlock)
            \(studentContext)
            \(subjectPrompt)
            \(knowledgeBlock)
            VOICE MODE: Maximum 2-3 sentences. No Markdown, LaTeX, or symbols. Speak naturally, as in oral conversation. Always respond in Spanish.
            """
        }

        return """
        \(identityBlock)
        \(studentContext)
        \(subjectPrompt)
        \(knowledgeBlock)
        Always respond in Spanish. Give clear, structured responses. Never mention internal tools to the student. Do not repeat data a tool already returned; integrate results naturally into your response.
        \(toolInstructions)
        """
    }

    /// Builds concise tool usage instructions. Kept short to preserve context window on-device.
    /// Since includesSchemaInInstructions=false on all tools, these instructions are the only
    /// guidance the model gets about tool parameters.
    private func buildToolInstructions(for subject: Subject, includeImageInstructions: Bool) -> String {
        var lines: [String] = []

        if includeImageInstructions {
            lines.append("USE generateEducationalImage when \(studentName) asks to see something visual (animals, atoms, planets, cells, monuments). Parameters: category (animal/plant/place/space/anatomy/object/nature/art), imagePrompt (English), reasonForImage (Spanish).")
        }

        switch subject {
        case .math, .physics, .chemistry, .open:
            lines.append("USE generate3DGeometry for 3D shapes. Parameters: shape (sphere/cube/cylinder/pyramid/torus/cone/capsule), color (name), scale (0.5-2.0), animation (none/rotate/pulse/bounce), caption (optional).")
        default:
            break
        }

        if quizTool != nil {
            lines.append("USE generateQuizQuestion to test comprehension or when asked for a quiz. Parameters: question (Spanish), options (exactly 4, Spanish), correctAnswer (matching option), explanation (Spanish), relatedConcept, difficulty (easy/medium/hard).")
        }

        if questTool != nil {
            lines.append("USE generateDailyQuest when asked for a mission or challenge. Parameters: questType (quick/challenge/epic), difficulty (easy/medium/hard), title (Spanish), description (Spanish), relatedConcepts, subjectId.")
        }

        // Memory tools are always present — include their parameter hints
        lines.append("USE storeStudentKnowledge to record what the student knows or struggles with. Parameters: knowledge (fact), category (concept/difficulty/interest/preference), masteryLevel (0.0-1.0).")
        lines.append("USE recallStudentKnowledge to retrieve stored student data. Parameters: queryType (all/concepts/difficulties/interests/profile), topic (optional filter).")

        guard !lines.isEmpty else { return "" }
        return "AVAILABLE TOOLS:\n" + lines.joined(separator: "\n")
    }

    /// Builds Nova's identity block — who she is, how she relates to the student
    private func buildIdentityBlock() -> String {
        return """
        Your name is Nova. You are the personal AI tutor of \(studentName). \
        You know \(studentName) and always address your student by name. \
        If asked your name, respond "Me llamo Nova" (in Spanish). \
        If asked the student's name, respond that their name is \(studentName). \
        Always respond in Spanish.
        """
    }

    /// Builds the student context with education level and pedagogical adaptation
    private func buildStudentContext() -> String {
        return """
        Student \(studentName) is at \(educationLevel.rawValue) level. \
        \(educationLevel.pedagogicalContext)
        """
    }

    /// Builds compact knowledge context from student memory (if available)
    private func buildKnowledgeBlock() -> String {
        guard !studentKnowledgeContext.isEmpty,
              studentKnowledgeContext != "No hay información previa sobre este estudiante." else {
            return ""
        }

        // Truncate to avoid context overflow
        let truncated = studentKnowledgeContext.count > 400
            ? String(studentKnowledgeContext.prefix(400)) + "..."
            : studentKnowledgeContext
        return "Prior learning context for \(studentName):\n\(truncated)"
    }

}

enum NovaError: Error, LocalizedError {
    case noSession
    case generationCancelled
    case modelUnavailable(String)
    case contextLimitExceeded
    case toolCallFailed(String)
    case imageGenerationFailed(String)
    case streamingFailed(Error)

    var errorDescription: String? {
        switch self {
        case .noSession:
            return "No hay sesión activa. Por favor reinicia el chat."
        case .generationCancelled:
            return "La generación fue cancelada."
        case .modelUnavailable(let reason):
            return "El modelo no está disponible: \(reason)"
        case .contextLimitExceeded:
            return "La conversación es muy larga. Por favor, inicia una nueva."
        case .toolCallFailed(let toolName):
            return "Error al usar \(toolName). Intenta de nuevo."
        case .imageGenerationFailed(let reason):
            return "No se pudo generar la imagen: \(reason)"
        case .streamingFailed:
            return "Error al generar la respuesta. Intenta de nuevo."
        }
    }

    var recoverySuggestion: String? {
        switch self {
        case .noSession:
            return "Sal del chat y vuelve a entrar."
        case .contextLimitExceeded:
            return "Limpia el historial de esta conversación."
        case .modelUnavailable:
            return "Verifica que Apple Intelligence esté habilitado en Ajustes > Apple Intelligence."
        default:
            return nil
        }
    }
}


